In [1]:
import numpy as np
import sys
sys.path += ['../../general', '..']
from eleven_regressions_model import ElevenRegressionsModel
from one_position_regression_conv_model import OnePositionRegressionConvModel
from pool import Pool
from collections import Counter
from metric import metric

/usr/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
pool = Pool('../../data')
train_pool, test_pool = pool.train_test_split()

In [3]:
model = ElevenRegressionsModel(len(pool.features[0]), OnePositionRegressionConvModel)
model.teach(train_pool)

Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Epoch 1/10
2283/2283 [==============================] - 4s - loss: 79.2045     
Epoch 2/10
2283/2283 [==============================] - 2s - loss: 5.5093     
Epoch 3/10
2283/2283 [==============================] - 2s - loss: 2.6762     
Epoch 4/10
2283/2283 [==============================] - 2s - loss: 0.1581     
Epoch 5/10
2283/2283 [==============================] - 2s - loss: 0.1493     
Epoch 6/10
2283/2283 [==============================] - 2s - loss: 0.1456     
Epoch 7/10
2283/2283 [==============================] - 2s - loss: 0.1433     
Epoch 8/10
2283/2283 [==============================] - 2s - loss: 0.1415     
Epoch 9/10
2283/2283 [==============================] - 2s - loss: 0.1399     
Epoch 10/10
2283/2283 [==============================] - 2s - loss: 0.1383     
Epoch 1/10
2731/2731 [==============================] - 3s - l

2396/2396 [==============================] - 2s - loss: 0.1204     
Epoch 7/10
2396/2396 [==============================] - 2s - loss: 0.1161     
Epoch 8/10
2396/2396 [==============================] - 2s - loss: 0.1172     
Epoch 9/10
2396/2396 [==============================] - 2s - loss: 0.1672     
Epoch 10/10
2396/2396 [==============================] - 2s - loss: 0.1366     


In [4]:
def test(model, pool):
    position_prediction = model.predict_positions(pool)
    print(metric(
        position_prediction, pool.positions,
        pool.targets, pool.probas
    ))
    print(Counter(position_prediction))

In [5]:
test(model, train_pool)

[ 0.06  0.03 -0.09  0.17  0.15 -0.01 -0.1  -0.14 -0.12 -0.01] 0.17 1.0
[-0.03  0.05  0.   -0.03 -0.09  0.07  0.05 -0.02 -0.    0.01] 0.07 1.0
[-0.08 -0.02 -0.    0.03  0.02 -0.01  0.07 -0.25  0.06 -0.08] 0.07 1.0
[-0.02 -0.08 -0.07  0.   -0.01  0.04 -0.01  0.02 -0.03 -0.13] 0.04 1.0
[-0.01  0.04 -0.02 -0.15 -0.24  0.   -0.04  0.05  0.02 -0.02] 0.05 1.0
[ 0.01 -0.2  -0.1  -0.08 -0.01  0.03 -0.02 -0.    0.08  0.01] 0.08 1.0
[-0.03 -0.19 -0.05 -0.26 -0.12 -0.04  0.08 -0.1  -0.07 -0.05] 0.08 1.0
[-0.01  0.   -0.03  0.21 -0.01 -0.04 -0.03  0.    0.1   0.02] 0.21 -2.7
[-0.04 -0.04  0.05 -0.06 -0.07 -0.03  0.05  0.15  0.15  0.09] 0.15 1.0
[ 0.06  0.09  0.02  0.06 -0.11 -0.08 -0.26  0.04  0.09 -0.07] 0.09 -1.6
[-0.04 -0.22  0.08  0.07 -0.05 -0.01  0.02 -0.03  0.19  0.03] 0.19 1.0
[-0.12  0.26  0.04 -0.1  -0.05 -0.11 -0.01  0.15 -0.09 -0.1 ] 0.26 1.0
[-0.01 -0.02  0.03 -0.15 -0.12 -0.02 -0.02 -0.07 -0.   -0.02] 0.03 1.0
[-0.02  0.17  0.13 -0.16  0.04 -0.02 -0.05 -0.03 -0.11 -0.  ] 0.17 1.0
[-0.

[ 0.05 -0.01 -0.03 -0.04  0.01  0.01 -0.   -0.05 -0.08 -0.02] 0.05 1.0
[-0.01  0.03 -0.07 -0.1  -0.13 -0.05  0.01 -0.09  0.09  0.02] 0.09 -3.08
[-0.03  0.05 -0.08 -0.09 -0.    0.   -0.02 -0.12 -0.21 -0.04] 0.05 1.0
[-0.06 -0.37 -0.08  0.12 -0.05 -0.02  0.02  0.08 -0.02  0.  ] 0.12 1.0
[-0.05 -0.06 -0.05  0.08 -0.06 -0.02 -0.04 -0.01  0.03  0.05] 0.08 1.0
[-0.07 -0.12 -0.04 -0.16 -0.08 -0.01  0.1   0.02 -0.03 -0.11] 0.1 1.0
[-0.03 -0.02  0.14 -0.07  0.21  0.12 -0.16 -0.07 -0.07 -0.23] 0.21 1.0
[-0.06 -0.04 -0.07 -0.16  0.08 -0.04  0.06 -0.07  0.01 -0.06] 0.08 1.0
[-0.03  0.01 -0.17 -0.04 -0.04 -0.06 -0.03  0.06 -0.05  0.04] 0.06 -2.31
[ 0.   -0.08  0.02  0.02 -0.08  0.11  0.02 -0.11 -0.14  0.02] 0.11 1.0
[-0.    0.05 -0.07 -0.01 -0.05  0.02  0.03  0.    0.02  0.12] 0.12 1.0
[-0.02 -0.2  -0.06 -0.4  -0.04 -0.04  0.03 -0.04 -0.02 -0.04] 0.03 1.0
[-0.05 -0.12 -0.01 -0.11 -0.06  0.03 -0.03 -0.07  0.08 -0.17] 0.08 1.0
[-0.11  0.01  0.04 -0.21  0.01 -0.03  0.05 -0.26 -0.12  0.08] 0.08 1.0
[-0