In [1]:
import numpy as np

In [2]:
x = np.load('res/0-1.txt')

In [3]:
np.shape(x)

(2, 10, 7)

In [4]:
np.arange(np.shape(x)[1])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
x

array([[[0.02007608, 0.8795435 , 0.02007608, 0.02007608, 0.02007608,
         0.02007608, 0.02007608],
        [0.02007608, 0.8795435 , 0.02007608, 0.02007608, 0.02007608,
         0.02007608, 0.02007608],
        [0.02007608, 0.8795435 , 0.02007608, 0.02007608, 0.02007608,
         0.02007608, 0.02007608],
        [0.02007608, 0.8795435 , 0.02007608, 0.02007608, 0.02007608,
         0.02007608, 0.02007608],
        [0.02021818, 0.87852416, 0.02038492, 0.02021818, 0.02021818,
         0.02021818, 0.02021818],
        [0.02021818, 0.87852416, 0.02038492, 0.02021818, 0.02021818,
         0.02021818, 0.02021818],
        [0.02021818, 0.87852416, 0.02038492, 0.02021818, 0.02021818,
         0.02021818, 0.02021818],
        [0.02021818, 0.87852416, 0.02038492, 0.02021818, 0.02021818,
         0.02021818, 0.02021818],
        [0.02021818, 0.87852416, 0.02038492, 0.02021818, 0.02021818,
         0.02021818, 0.02021818],
        [0.02021818, 0.87852416, 0.02038492, 0.02021818, 0.02021818,
    

In [10]:
repeated_arange = np.repeat(
    [np.repeat([np.arange(np.shape(x)[2])], np.shape(x)[1], axis=0)],
    np.shape(x)[0],
    axis=0
)

In [16]:
np.sum(repeated_arange * x, axis=-1)

array([[1.28106517, 1.28106517, 1.28106517, 1.28106517, 1.28322132,
        1.28322132, 1.28322132, 1.28322132, 1.28322132, 1.28322132],
       [2.14136056, 2.14136056, 2.14136056, 2.14136056, 2.14053259,
        2.14053259, 2.14053259, 2.14053259, 2.14053259, 2.14053259]])

In [17]:
np.round(np.sum(repeated_arange * x, axis=-1))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])