In [1]:
import numpy as np
from eleven_regressions_model import ElevenRegressionsModel
from one_position_linear_model import OnePositionLinearModel
import sys
sys.path.append('../general')
from pool import Pool
from collections import Counter
from metric import metric

/usr/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
pool = Pool('../data')
train_pool, test_pool = pool.train_test_split()

In [3]:
model = ElevenRegressionsModel(len(pool.features[0]), OnePositionLinearModel)
model.teach(train_pool)

 position loss 1: 0.11566148698329926
 position loss 2: 0.10669079422950745
 position loss 3: 0.11445809155702591
 position loss 4: 0.11637594550848007
 position loss 5: 0.09914213418960571
 position loss 6: 0.1396811455488205
 position loss 7: 0.12067918479442596
 position loss 8: 0.13178697228431702
 position loss 9: 0.12260795384645462
 position loss 10: 0.1080358624458313


In [4]:
def test_pool(model, pool):
    position_prediction = model.predict_positions(pool)
    print(metric(
        position_prediction, pool.positions,
        pool.targets, pool.probas
    ))
    print(Counter(position_prediction))

In [5]:
test_pool(model, train_pool)

[-0.01  0.15 -0.07  0.04  0.02 -0.16 -0.11  0.05 -0.13  0.08] 0.15 1.0
[ 0.05 -0.09 -0.07 -0.1   0.19 -0.16  0.05 -0.2  -0.23 -0.26] 0.19 -1.6
[ 0.16 -0.07  0.11 -0.01  0.09 -0.24 -0.17 -0.17  0.05 -0.03] 0.16 1.0
[-0.61  0.51 -0.81  0.01 -0.03  0.12  0.07  0.08 -0.53 -0.01] 0.51 1.0
[-0.22 -0.48 -0.08  0.16  0.1  -0.05  0.06  0.04 -0.15 -0.16] 0.16 1.0
[ 0.04  0.23 -0.19  0.03  0.23 -0.1   0.11  0.11  0.04 -0.27] 0.23 1.0
[ 0.04  0.08  0.22 -0.27  0.24 -0.07 -0.17 -0.23  0.35 -0.14] 0.35 1.0
[ 0.1  -0.1  -0.41  0.1   0.01  0.16  0.09 -0.08 -0.12 -0.49] 0.16 1.0
[ 0.33  0.18  0.07 -0.08 -0.07 -0.17 -0.04 -0.23  0.21 -0.24] 0.33 1.0
[-0.56 -0.6   0.28  0.04 -0.21  0.23  0.03 -0.17 -0.15  0.17] 0.28 -1.6
[ 0.02 -0.04  0.09 -0.15 -0.14 -0.    0.18 -0.05  0.02  0.03] 0.18 1.0
[-0.14  0.39  0.28  0.07  0.01 -0.33  0.01 -0.22  0.36 -0.26] 0.39 -1.91
[-0.13 -0.28 -0.1   0.14 -0.04 -0.21  0.07 -0.08  0.18 -0.27] 0.18 -1.91
[-0.29 -0.25 -0.32 -0.27 -0.07 -0.05 -0.15 -0.07 -0.08  0.05] 0.05 1.0


[-0.09  0.02 -0.23 -0.2   0.14 -0.29  0.25 -0.08 -0.04  0.19] 0.25 -1.55
[ 0.05 -0.07 -0.22  0.11 -0.1  -0.21  0.28 -0.27  0.01  0.18] 0.28 -1.64
[-0.06 -0.24  0.19  0.08  0.23 -0.33  0.01 -0.12  0.11  0.2 ] 0.23 1.0
[ 0.32 -0.31  0.35 -0.2  -0.19 -0.21 -0.25 -0.13 -0.15 -0.23] 0.35 1.0
[-0.23 -0.22 -0.1   0.03 -0.18  0.46 -0.04 -0.19  0.33  0.21] 0.46 -0.91
[-0.09 -0.49 -0.27 -0.12  0.04  0.12 -0.23  0.11 -0.04 -0.39] 0.12 -1.6
[ 0.11 -0.07 -0.84  0.19  0.04 -0.13  0.26  0.28  0.13 -0.25] 0.28 1.0
[-0.62 -0.01 -0.   -0.14  0.23 -0.36  0.04 -0.09 -0.04  0.05] 0.23 -1.43
[-0.02  0.13  0.05 -0.42  0.13  0.09 -0.31  0.04 -0.2  -0.47] 0.13 1.0
[-0.02  0.06  0.31  0.06  0.14 -0.08  0.06 -0.09 -0.09 -0.11] 0.31 1.0
[-0.05 -0.2   0.33 -0.32  0.24 -0.22 -0.12  0.02  0.02 -0.1 ] 0.33 1.0
[-0.13 -0.1   0.11 -0.08 -0.15 -0.03  0.23  0.21 -0.01 -0.03] 0.23 1.0
[-0.68  0.16  0.09 -0.37  0.23 -0.21 -0.14  0.27 -0.26  0.17] 0.27 1.0
[-0.52 -0.01  0.84 -0.14 -0.12  0.02 -1.08  0.57  0.47 -0.38] 0.84 -