In [1]:
import numpy as np
from one_regression_conv_model import OneRegressionConvModel
import sys
sys.path.append('../general')
from pool import Pool
from collections import Counter
from metric import metric

/usr/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
pool = Pool('../data')
train_pool, test_pool = pool.train_test_split()

In [3]:
model = OneRegressionConvModel(len(pool.regression_features[0]))

Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead


In [4]:
model.teach(
    train_pool.regression_features, train_pool.regression_prediction
)

Epoch 1/5
63000/63000 [==============================] - 19s - loss: 0.4689    
Epoch 2/5
63000/63000 [==============================] - 18s - loss: 0.1444    
Epoch 3/5
63000/63000 [==============================] - 18s - loss: 0.1443    
Epoch 4/5
63000/63000 [==============================] - 18s - loss: 0.1443    
Epoch 5/5
63000/63000 [==============================] - 18s - loss: 0.1443    


In [ ]:
def test_pool(model, pool):
    position_prediction = model.predict_positions(pool)
    print(metric(
        position_prediction, pool.positions,
        pool.targets, pool.probas
    ))
    print(Counter(position_prediction))

In [ ]:
test_pool(model, train_pool)

[[-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]] -0.02 -0.91
[[-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]] -0.02 -1.91
[[-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]] -0.02 -1.6
[[-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]] -0.02 1.0
[[-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]] -0.02 -1.6
[[-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]] -0.02 1.0
[[-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]] -0.02 -0.84
[[-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]] -0.02 1.0
[[-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]] -0.02 -0.89
[[-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
 [-0.02]
