In [1]:
import numpy as np
from one_regression_conv_model import OneRegressionConvModel
import sys
sys.path.append('../general')
from pool import Pool
from collections import Counter
from metric import metric

/usr/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
pool = Pool('../data')
train_pool, test_pool = pool.train_test_split()

In [3]:
model = OneRegressionConvModel(len(pool.regression_features[0]))

Instructions for updating:
keep_dims is deprecated, use keepdims instead


In [4]:
model.teach(
    train_pool.regression_features, train_pool.regression_prediction
)

train loss: 0.03637237846851349
train loss: 0.19713985919952393
train loss: 0.07982906699180603
train loss: 0.18841642141342163
train loss: 0.12735974788665771
train loss: 0.10855919122695923
train loss: 0.056889377534389496
train loss: 0.053132690489292145
train loss: 0.07278313487768173
train loss: 0.16864143311977386
train loss: 0.05144477263092995
train loss: 0.036391567438840866
train loss: 0.17042018473148346
train loss: 0.0234375
train loss: 0.16884921491146088
train loss: 0.16295860707759857
train loss: 0.15250243246555328
train loss: 0.10518992692232132
train loss: 0.08203630149364471
train loss: 0.10277321189641953
train loss: 0.09230522811412811
train loss: 0.09809082001447678
train loss: 0.03343117982149124
train loss: 0.11530152708292007
train loss: 0.1611602008342743
train loss: 0.16287972033023834
train loss: 0.28567078709602356
train loss: 0.10944138467311859
train loss: 0.1553681343793869
train loss: 0.07443708926439285
train loss: 0.11615820229053497
train loss: 0.124

train loss: 0.15965330600738525
train loss: 0.24262383580207825
train loss: 0.06687500327825546
train loss: 0.14044983685016632
train loss: 0.07334625720977783
train loss: 0.09662367403507233
train loss: 0.1265375018119812
train loss: 0.10896970331668854
train loss: 0.15506720542907715
train loss: 0.18418554961681366
train loss: 0.24310846626758575
train loss: 0.08362898230552673
train loss: 0.21454884111881256
train loss: 0.08011773228645325
train loss: 0.12282833456993103
train loss: 0.12221032381057739
train loss: 0.16707178950309753
train loss: 0.14984199404716492
train loss: 0.11815405637025833
train loss: 0.1564485728740692
train loss: 0.21101076900959015
train loss: 0.15983889997005463
train loss: 0.2275451421737671
train loss: 0.06233127415180206
train loss: 0.03775685653090477
train loss: 0.22097501158714294
train loss: 0.12413260340690613
train loss: 0.05125000327825546
train loss: 0.19332993030548096
train loss: 0.08449273556470871
train loss: 0.17639732360839844
train loss:

train loss: 0.06449273228645325
train loss: 0.2198098599910736
train loss: 0.1400146484375
train loss: 0.17551229894161224
train loss: 0.10363943129777908
train loss: 0.3081233501434326
train loss: 0.11034251749515533
train loss: 0.16486330330371857
train loss: 0.2081500142812729
train loss: 0.15366743505001068
train loss: 0.028867730870842934
train loss: 0.15570910274982452
train loss: 0.22345732152462006
train loss: 0.09984879195690155
train loss: 0.1507013589143753
train loss: 0.06521450728178024
train loss: 0.07230523228645325
train loss: 0.14193284511566162
train loss: 0.052305229008197784
train loss: 0.08546607196331024
train loss: 0.1562633216381073
train loss: 0.1001717820763588
train loss: 0.10722361505031586
train loss: 0.2490777224302292
train loss: 0.0390625
train loss: 0.15848620235919952
train loss: 0.22939063608646393
train loss: 0.07108812779188156
train loss: 0.1940118670463562
train loss: 0.08706732094287872
train loss: 0.07063186168670654
train loss: 0.16308841109275

train loss: 0.29880809783935547
train loss: 0.09107907116413116
train loss: 0.13214141130447388
train loss: 0.2569085359573364
train loss: 0.14281153678894043
train loss: 0.13325737416744232
train loss: 0.07098105549812317
train loss: 0.12232965230941772
train loss: 0.1707604080438614
train loss: 0.06671915203332901
train loss: 0.07408223301172256
train loss: 0.16882577538490295
train loss: 0.13129600882530212
train loss: 0.08356571942567825
train loss: 0.17378732562065125
train loss: 0.1261242926120758
train loss: 0.07468750327825546
train loss: 0.06490081548690796
train loss: 0.1997617781162262
train loss: 0.3018014430999756
train loss: 0.11966255307197571
train loss: 0.17653723061084747
train loss: 0.06021680310368538
train loss: 0.34240806102752686
train loss: 0.04426484555006027
train loss: 0.28865230083465576
train loss: 0.25442731380462646
train loss: 0.1047554761171341
train loss: 0.08526552468538284
train loss: 0.06687500327825546
train loss: 0.08801211416721344
train loss: 0.

train loss: 0.34582898020744324
train loss: 0.11486418545246124
train loss: 0.13936808705329895
train loss: 0.22562523186206818
train loss: 0.103045754134655
train loss: 0.10934186726808548
train loss: 0.026250001043081284
train loss: 0.08098107576370239
train loss: 0.13236373662948608
train loss: 0.11678220331668854
train loss: 0.1181497573852539
train loss: 0.07903530448675156
train loss: 0.19696778059005737
train loss: 0.1701306700706482
train loss: 0.1413109004497528
train loss: 0.16039428114891052
train loss: 0.07574272900819778
train loss: 0.11650929600000381
train loss: 0.19860130548477173
train loss: 0.1362374871969223
train loss: 0.16602808237075806
train loss: 0.2742956578731537
train loss: 0.14438359439373016
train loss: 0.10759785771369934
train loss: 0.09315671026706696
train loss: 0.17452344298362732
train loss: 0.13080912828445435
train loss: 0.08000686019659042
train loss: 0.26541823148727417
train loss: 0.15342874825000763
train loss: 0.11769251525402069
train loss: 0.

train loss: 0.1597243696451187
train loss: 0.11389156430959702
train loss: 0.19048450887203217
train loss: 0.04166756570339203
train loss: 0.11785319447517395
train loss: 0.10708554089069366
train loss: 0.13825851678848267
train loss: 0.036391567438840866
train loss: 0.19737961888313293
train loss: 0.1321038454771042
train loss: 0.11465813219547272
train loss: 0.08986882865428925
train loss: 0.17728328704833984
train loss: 0.1580658257007599
train loss: 0.14087064564228058
train loss: 0.11035646498203278
train loss: 0.15751974284648895
train loss: 0.207004114985466
train loss: 0.13457340002059937
train loss: 0.06227919086813927
train loss: 0.23399929702281952
train loss: 0.15554018318653107
train loss: 0.11808112263679504
train loss: 0.22642342746257782
train loss: 0.07488227635622025
train loss: 0.16630563139915466
train loss: 0.21174262464046478
train loss: 0.116179920732975
train loss: 0.1948842853307724
train loss: 0.09031250327825546
train loss: 0.19999676942825317
train loss: 0.1

train loss: 0.20186662673950195
train loss: 0.2071496844291687
train loss: 0.24242421984672546
train loss: 0.11504997313022614
train loss: 0.2762763202190399
train loss: 0.17444400489330292
train loss: 0.15904945135116577
train loss: 0.11481571197509766
train loss: 0.11433400958776474
train loss: 0.17848514020442963
train loss: 0.11633975058794022
train loss: 0.0546875
train loss: 0.09601718932390213
train loss: 0.10614411532878876
train loss: 0.028579067438840866
train loss: 0.1057581976056099
train loss: 0.16173437237739563
train loss: 0.16886818408966064
train loss: 0.13267099857330322
train loss: 0.14091414213180542
train loss: 0.15359514951705933
train loss: 0.06991975754499435
train loss: 0.1445445716381073
train loss: 0.0390625
train loss: 0.3025832772254944
train loss: 0.12487602978944778
train loss: 0.17185792326927185
train loss: 0.18708102405071259
train loss: 0.0625
train loss: 0.136633962392807
train loss: 0.046875
train loss: 0.1313496083021164
train loss: 0.1415302157402

train loss: 0.15131673216819763
train loss: 0.1862657070159912
train loss: 0.06054796278476715
train loss: 0.11213429272174835
train loss: 0.06476563215255737
train loss: 0.1654578596353531
train loss: 0.22713422775268555
train loss: 0.17940214276313782
train loss: 0.06554795801639557
train loss: 0.08567315340042114
train loss: 0.16182443499565125
train loss: 0.1464151293039322
train loss: 0.20178291201591492
train loss: 0.1984279602766037
train loss: 0.08815434575080872
train loss: 0.20640671253204346
train loss: 0.12991750240325928
train loss: 0.21734194457530975
train loss: 0.25214576721191406
train loss: 0.11077920347452164
train loss: 0.03587578982114792
train loss: 0.03759677708148956
train loss: 0.14141276478767395
train loss: 0.11167363077402115
train loss: 0.04521450400352478
train loss: 0.17744901776313782
train loss: 0.07565134763717651
train loss: 0.0390625
train loss: 0.10229577124118805
train loss: 0.15274733304977417
train loss: 0.28789788484573364
train loss: 0.31369328

train loss: 0.14068934321403503
train loss: 0.15100273489952087
train loss: 0.08288806676864624
train loss: 0.09904839843511581
train loss: 0.044492729008197784
train loss: 0.10419227927923203
train loss: 0.24026291072368622
train loss: 0.23830336332321167
train loss: 0.17087915539741516
train loss: 0.07965999841690063
train loss: 0.08117295801639557
train loss: 0.06288807094097137
train loss: 0.12827982008457184
train loss: 0.03209276497364044
train loss: 0.13324588537216187
train loss: 0.11568199843168259
train loss: 0.3872813284397125
train loss: 0.044492729008197784
train loss: 0.06343750655651093
train loss: 0.17543107271194458
train loss: 0.11774357408285141
train loss: 0.3849647343158722
train loss: 0.1837901473045349
train loss: 0.11683320254087448
train loss: 0.14367078244686127
train loss: 0.10886307060718536
train loss: 0.28325945138931274
train loss: 0.13588392734527588
train loss: 0.053621359169483185
train loss: 0.14565443992614746
train loss: 0.14673365652561188
train lo

In [ ]:
def test_pool(model, pool):
    position_prediction = model.predict_positions(pool)
    print(metric(
        position_prediction, pool.positions,
        pool.targets, pool.probas
    ))
    print(Counter(position_prediction))

In [ ]:
test_pool(model, train_pool)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 -1.6
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 -1.47
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 -1.43
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 -1.64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 -3.08
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 -1.64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
