In [1]:
import numpy as np
from one_regression_conv_model import OneRegressionConvModel
import sys
sys.path.append('../general')
from pool import Pool
from collections import Counter
from metric import metric

/usr/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
pool = Pool('../data')
train_pool, test_pool = pool.train_test_split()

In [3]:
model = OneRegressionConvModel(len(pool.regression_features[0]))

Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead


In [4]:
model.teach(
    train_pool.regression_features, train_pool.regression_prediction
)

Epoch 1/1
63000/63000 [==============================] - 393s - loss: 37.8147   


In [5]:
model.sequential_model.get_weights()

[array([[[-0.21526007, -0.15739307, -0.26843244,  0.19825272,
          -0.07839174, -0.0580819 , -0.1250507 ,  0.02956366]],
 
        [[ 0.20784621,  0.13403824, -0.33487988,  0.00111586,
          -0.11043929,  0.06991468,  0.15910932,  0.15662503]],
 
        [[ 0.01827882,  0.32707614,  0.3142721 ,  0.04662881,
          -0.13791735, -0.22263372, -0.19188686,  0.23392922]],
 
        [[ 0.29728553,  0.2155772 ,  0.11318679, -0.14520004,
           0.00105405, -0.22326306,  0.32161614, -0.19406094]],
 
        [[ 0.2700608 , -0.11426603,  0.15386468, -0.31261027,
          -0.20497544, -0.13491943, -0.14031783,  0.05402852]]],
       dtype=float32),
 array([-0.01425211, -0.0057043 , -0.01448014, -0.01437347, -0.01119998,
        -0.00644401, -0.00570873, -0.01428207], dtype=float32),
 array([[[ 2.08573595e-01, -2.45928437e-01,  9.90838259e-02,
          -2.62879044e-01, -5.48778242e-03, -5.38601689e-02,
          -4.38569747e-02,  9.74569470e-02,  3.23856845e-02,
           2.06377

In [6]:
def test(model, pool):
    position_prediction = model.predict_positions(pool)
    print(metric(
        position_prediction, pool.positions,
        pool.targets, pool.probas
    ))
    print(Counter(position_prediction))

In [7]:
test(model, test_pool)

[[-0.03]
 [-0.03]
 [-0.03]
 [-0.03]
 [-0.03]
 [-0.03]
 [-0.03]
 [-0.03]
 [-0.03]
 [-0.03]] -0.03 -1.6
[[0.03]
 [0.03]
 [0.04]
 [0.03]
 [0.03]
 [0.03]
 [0.03]
 [0.03]
 [0.03]
 [0.04]] 0.04 -0.6
[[-0.21]
 [-0.21]
 [-0.21]
 [-0.21]
 [-0.21]
 [-0.21]
 [-0.21]
 [-0.21]
 [-0.21]
 [-0.21]] -0.21 1.0
[[-0.44]
 [-0.44]
 [-0.44]
 [-0.44]
 [-0.44]
 [-0.44]
 [-0.44]
 [-0.44]
 [-0.44]
 [-0.44]] -0.44 -0.6
[[0.37]
 [0.36]
 [0.36]
 [0.36]
 [0.36]
 [0.37]
 [0.36]
 [0.36]
 [0.36]
 [0.36]] 0.37 -0.6
[[-0.08]
 [-0.07]
 [-0.07]
 [-0.09]
 [-0.08]
 [-0.08]
 [-0.08]
 [-0.08]
 [-0.08]
 [-0.08]] -0.07 -3.13
[[-0.09]
 [-0.07]
 [-0.07]
 [-0.09]
 [-0.07]
 [-0.07]
 [-0.07]
 [-0.07]
 [-0.07]
 [-0.07]] -0.07 -1.6
[[0.63]
 [0.64]
 [0.65]
 [0.63]
 [0.63]
 [0.64]
 [0.63]
 [0.64]
 [0.64]
 [0.64]] 0.65 1.0


KeyboardInterrupt: 