In [1]:
import numpy as np
from one_regression_conv_model import OneRegressionConvModel
import sys
sys.path.append('../general')
from pool import Pool
from collections import Counter
from metric import metric

/usr/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
pool = Pool('../data')
train_pool, test_pool = pool.train_test_split()

In [3]:
model = OneRegressionConvModel(len(pool.regression_features[0]))

Instructions for updating:
keep_dims is deprecated, use keepdims instead


In [4]:
model.teach(
    train_pool.regression_features, train_pool.regression_prediction
)

train loss: 1.9589366912841797
train loss: 1.3606846332550049
train loss: 1.5223381519317627
train loss: 1.0814695358276367
train loss: 1.4652642011642456
train loss: 7.039449691772461
train loss: 1.3063042163848877
train loss: 1.1522303819656372
train loss: 1.5575515031814575
train loss: 1.2472100257873535
train loss: 1.9945729970932007
train loss: 1.4538553953170776
train loss: 1.167986273765564
train loss: 0.9795122146606445
train loss: 1.248734951019287
train loss: 1.0043140649795532
train loss: 1.3826239109039307
train loss: 0.77959805727005
train loss: 1.3426685333251953
train loss: 1.6942015886306763
train loss: 0.998526930809021
train loss: 0.9744669198989868
train loss: 1.0791118144989014
train loss: 1.2497854232788086
train loss: 1.015779972076416
train loss: 1.3835099935531616
train loss: 1.7497148513793945
train loss: 1.0421018600463867
train loss: 1.5574495792388916
train loss: 0.793067991733551
train loss: 0.8703233003616333
train loss: 1.4878382682800293
train loss: 0.84

train loss: 0.22915971279144287
train loss: 0.26566100120544434
train loss: 0.23277950286865234
train loss: 0.23158548772335052
train loss: 0.08902153372764587
train loss: 0.08435428142547607
train loss: 0.15295755863189697
train loss: 0.1441856324672699
train loss: 0.19340351223945618
train loss: 0.25267595052719116
train loss: 0.22158178687095642
train loss: 0.15120281279087067
train loss: 0.05970785766839981
train loss: 0.16649936139583588
train loss: 0.1490122377872467
train loss: 0.1308123767375946
train loss: 0.10482489317655563
train loss: 0.13756854832172394
train loss: 0.14611364901065826
train loss: 0.18702980875968933
train loss: 0.09628468751907349
train loss: 0.12012938410043716
train loss: 0.14422616362571716
train loss: 0.14084839820861816
train loss: 0.2639535069465637
train loss: 0.1734391301870346
train loss: 0.08125700801610947
train loss: 0.16372913122177124
train loss: 0.22989752888679504
train loss: 0.05182935297489166
train loss: 0.153351828455925
train loss: 0.1

train loss: 0.14686447381973267
train loss: 0.22120757400989532
train loss: 0.10029507428407669
train loss: 0.1599971204996109
train loss: 0.1646302044391632
train loss: 0.16308850049972534
train loss: 0.18547597527503967
train loss: 0.17231333255767822
train loss: 0.15350301563739777
train loss: 0.08852669596672058
train loss: 0.1435074359178543
train loss: 0.2021213173866272
train loss: 0.20164978504180908
train loss: 0.07368122786283493
train loss: 0.191722571849823
train loss: 0.11987058073282242
train loss: 0.11615370213985443
train loss: 0.1495310217142105
train loss: 0.08772329986095428
train loss: 0.1377517431974411
train loss: 0.1409764587879181
train loss: 0.3540341258049011
train loss: 0.06006643921136856
train loss: 0.1276051551103592
train loss: 0.23042479157447815
train loss: 0.14961358904838562
train loss: 0.10955607146024704
train loss: 0.36550450325012207
train loss: 0.1817210465669632
train loss: 0.19776058197021484
train loss: 0.41921234130859375
train loss: 0.196783

train loss: 0.061139460653066635
train loss: 0.11867816746234894
train loss: 0.13300877809524536
train loss: 0.1322852075099945
train loss: 0.019991736859083176
train loss: 0.23961615562438965
train loss: 0.10178277641534805
train loss: 0.16526833176612854
train loss: 0.14111928641796112
train loss: 0.08056531101465225
train loss: 0.15702542662620544
train loss: 0.18202990293502808
train loss: 0.1290556937456131
train loss: 0.1821603775024414
train loss: 0.15556281805038452
train loss: 0.12243109941482544
train loss: 0.23865297436714172
train loss: 0.158579021692276
train loss: 0.015819480642676353
train loss: 0.11042897403240204
train loss: 0.10310398042201996
train loss: 0.08843318372964859
train loss: 0.17864452302455902
train loss: 0.05017546936869621
train loss: 0.12852755188941956
train loss: 0.09689629077911377
train loss: 0.1872076839208603
train loss: 0.16795915365219116
train loss: 0.12191142141819
train loss: 0.12027736753225327
train loss: 0.07860531657934189
train loss: 0.

train loss: 0.058194391429424286
train loss: 0.2660571038722992
train loss: 0.21544212102890015
train loss: 0.10385522246360779
train loss: 0.08802776038646698
train loss: 0.20621223747730255
train loss: 0.0816456526517868
train loss: 0.0812481939792633
train loss: 0.09634104371070862
train loss: 0.054143309593200684
train loss: 0.23636206984519958
train loss: 0.1717955768108368
train loss: 0.14945410192012787
train loss: 0.10454557836055756
train loss: 0.06808146834373474
train loss: 0.1872938573360443
train loss: 0.1270611733198166
train loss: 0.12459778040647507
train loss: 0.07008983194828033
train loss: 0.12759310007095337
train loss: 0.07283768802881241
train loss: 0.10253050923347473
train loss: 0.20462052524089813
train loss: 0.0935279056429863
train loss: 0.10146595537662506
train loss: 0.11798151582479477
train loss: 0.1460302472114563
train loss: 0.0493086539208889
train loss: 0.3228648900985718
train loss: 0.1277942657470703
train loss: 0.18648695945739746
train loss: 0.104

train loss: 0.1779804676771164
train loss: 0.26866263151168823
train loss: 0.1410941481590271
train loss: 0.17612233757972717
train loss: 0.07336363196372986
train loss: 0.1812346875667572
train loss: 0.09706409275531769
train loss: 0.06200022995471954
train loss: 0.2288837730884552
train loss: 0.12333022803068161
train loss: 0.07303553819656372
train loss: 0.13272523880004883
train loss: 0.2642509341239929
train loss: 0.19788816571235657
train loss: 0.034466687589883804
train loss: 0.02031043916940689
train loss: 0.23394766449928284
train loss: 0.1138494610786438
train loss: 0.2763344943523407
train loss: 0.06951269507408142
train loss: 0.24335527420043945
train loss: 0.19727610051631927
train loss: 0.12372501939535141
train loss: 0.1722133457660675
train loss: 0.16725598275661469
train loss: 0.059164971113204956
train loss: 0.09817817807197571
train loss: 0.07878267019987106
train loss: 0.0758916586637497
train loss: 0.2377166450023651
train loss: 0.20162679255008698
train loss: 0.12

train loss: 0.08415361493825912
train loss: 0.07039212435483932
train loss: 0.09783907234668732
train loss: 0.08709897100925446
train loss: 0.19154366850852966
train loss: 0.21782508492469788
train loss: 0.22461193799972534
train loss: 0.07867196202278137
train loss: 0.26501619815826416
train loss: 0.14383234083652496
train loss: 0.14142417907714844
train loss: 0.08295077085494995
train loss: 0.11032114177942276
train loss: 0.2784498929977417
train loss: 0.10918589681386948
train loss: 0.08117296546697617
train loss: 0.19699214398860931
train loss: 0.13561785221099854
train loss: 0.2461313009262085
train loss: 0.22958530485630035
train loss: 0.1850912868976593
train loss: 0.09308189898729324
train loss: 0.17826834321022034
train loss: 0.1321372389793396
train loss: 0.16984832286834717
train loss: 0.20511142909526825
train loss: 0.10538625717163086
train loss: 0.12854938209056854
train loss: 0.10336554050445557
train loss: 0.16984805464744568
train loss: 0.1137215793132782
train loss: 0

train loss: 0.13356634974479675
train loss: 0.11063173413276672
train loss: 0.11730392277240753
train loss: 0.31000980734825134
train loss: 0.10667437314987183
train loss: 0.1344175934791565
train loss: 0.14832976460456848
train loss: 0.15029402077198029
train loss: 0.06808803975582123
train loss: 0.08202745020389557
train loss: 0.16129188239574432
train loss: 0.10962166637182236
train loss: 0.11464111506938934
train loss: 0.057006560266017914
train loss: 0.31267040967941284
train loss: 0.18560923635959625
train loss: 0.14242282509803772
train loss: 0.16407983005046844
train loss: 0.123166523873806
train loss: 0.13080337643623352
train loss: 0.08378277719020844
train loss: 0.20296907424926758
train loss: 0.021521372720599174
train loss: 0.13578073680400848
train loss: 0.05338185653090477
train loss: 0.19555886089801788
train loss: 0.21540406346321106
train loss: 0.1306002140045166
train loss: 0.1115027442574501
train loss: 0.08744610846042633
train loss: 0.09076736867427826
train loss:

train loss: 0.0784696638584137
train loss: 0.07237517088651657
train loss: 0.1452881246805191
train loss: 0.13320830464363098
train loss: 0.0895833671092987
train loss: 0.03145429864525795
train loss: 0.1927087903022766
train loss: 0.08471432328224182
train loss: 0.1888890117406845
train loss: 0.19054792821407318
train loss: 0.23827120661735535
train loss: 0.18868568539619446
train loss: 0.18356625735759735
train loss: 0.18442204594612122
train loss: 0.1303609013557434
train loss: 0.17201785743236542
train loss: 0.14199215173721313
train loss: 0.20425504446029663
train loss: 0.11652164161205292
train loss: 0.13340388238430023
train loss: 0.26975733041763306
train loss: 0.10454149544239044
train loss: 0.16159793734550476
train loss: 0.11829153448343277
train loss: 0.04194403812289238
train loss: 0.17984968423843384
train loss: 0.18452900648117065
train loss: 0.18535345792770386
train loss: 0.12148638814687729
train loss: 0.16368380188941956
train loss: 0.22934302687644958
train loss: 0.

In [5]:
def test_pool(model, pool):
    position_prediction = model.predict_positions(pool)
    print(metric(
        position_prediction, pool.positions,
        pool.targets, pool.probas
    ))
    print(Counter(position_prediction))

In [6]:
test_pool(model, train_pool)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 -1.6
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 -1.64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 -1.89
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 -1.6
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 -1.64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 -1.6
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 -1.91
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 -1.6
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
[0.01 0.01 0.01 0.01 0.02 0.01 0.01 0.02 0.02 0.01] 0.02 -0.91
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 -2.64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 -1.6
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 -1.91
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 -3.08
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 -1